@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "abstractFactory.AbstractFactoryMain#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "abstractFactory.AbstractFactoryMain",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1934373240 { 
   	label=abstractFactory
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1065962459 { 
   	label=AbstractFactoryMain
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstractFactoryMain1934373240XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="AbstractFactoryMain

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1303987192 { 
   	label=FactoryCreator
	labeljust=l
	fillcolor=white
	style=filled
   
   FactoryCreator1934373240XXXgetFactory1808118735[
	label="+ getFactory()"
	style=filled
	fillcolor=white
	tooltip="FactoryCreator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1316604044 { 
   	label=LoanFactory
	labeljust=l
	fillcolor=white
	style=filled
   
   LoanFactory1934373240XXXgetBank1808118735[
	label="+ getBank()"
	style=filled
	fillcolor=white
	tooltip="LoanFactory

null"
	fontcolor=darkgreen
];

LoanFactory1934373240XXXgetLoan1799740042[
	label="+ getLoan()"
	style=filled
	fillcolor=white
	tooltip="LoanFactory

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1504654640 { 
   	label=BOC
	labeljust=l
	fillcolor=white
	style=filled
   
   BOC1934373240XXXbankName0[
	label="+ bankName()"
	style=filled
	fillcolor=white
	tooltip="BOC

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1504660374 { 
   	label=HNB
	labeljust=l
	fillcolor=white
	style=filled
   
   HNB1934373240XXXbankName0[
	label="+ bankName()"
	style=filled
	fillcolor=white
	tooltip="HNB

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_549406752 { 
   	label=AbstactFactory
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstactFactory1934373240XXXgetBank1808118735[
	label="+ getBank()"
	style=filled
	fillcolor=white
	tooltip="AbstactFactory

null"
	fontcolor=darkgreen
];

AbstactFactory1934373240XXXgetLoan1799740042[
	label="+ getLoan()"
	style=filled
	fillcolor=white
	tooltip="AbstactFactory

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_731305816 { 
   	label=BankFactory
	labeljust=l
	fillcolor=white
	style=filled
   
   BankFactory1934373240XXXgetBank1808118735[
	label="+ getBank()"
	style=filled
	fillcolor=white
	tooltip="BankFactory

null"
	fontcolor=darkgreen
];

BankFactory1934373240XXXgetLoan1799740042[
	label="+ getLoan()"
	style=filled
	fillcolor=white
	tooltip="BankFactory

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
AbstactFactory1934373240XXXgetBank1808118735 -> BankFactory1934373240XXXgetBank1808118735;
AbstactFactory1934373240XXXgetBank1808118735 -> LoanFactory1934373240XXXgetBank1808118735;
AbstactFactory1934373240XXXgetLoan1799740042 -> BankFactory1934373240XXXgetLoan1799740042;
AbstactFactory1934373240XXXgetLoan1799740042 -> LoanFactory1934373240XXXgetLoan1799740042;
AbstractFactoryMain1934373240XXXmain1859653459 -> AbstactFactory1934373240XXXgetBank1808118735;
AbstractFactoryMain1934373240XXXmain1859653459 -> AbstactFactory1934373240XXXgetLoan1799740042;
AbstractFactoryMain1934373240XXXmain1859653459 -> BOC1934373240XXXbankName0;
AbstractFactoryMain1934373240XXXmain1859653459 -> FactoryCreator1934373240XXXgetFactory1808118735;
AbstractFactoryMain1934373240XXXmain1859653459 -> HNB1934373240XXXbankName0;
    
}
@enduml